### ISSUE TITLE
detecting ports the easy way

### ISSUE THREAD

**Issue by dominictarr** [nodejitsu/haibu-carapace#16]
figured out a waaaay simpler method to discover the port an app has started on

``` bash
lsof -a -p $PID -i TCP

COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    19423 dominic    5u  IPv4 244275      0t0  TCP *:8000 (LISTEN)
```

no need for complicated monkey patching or IPC.

**Comment by bmeck** [comment]
we do not have lsof on machines usually

**Comment by indexzero** [comment]
@dominictarr Interesting. We would have to run the command repeatedly until a port was returned since we're looking for the deterministic time at which the server in the process starts. 

Also, how would deal with multiple server programs? It's on the list of features we need to have eventually.

**Comment by dominictarr** [comment]
as I see it, the purpose of the auto detection feature is to create a good first use experience.

once someone is creating multi-server programs they are hooked, so it's simpler to give them a little configuration. 

the man page says that it runs on

```
Lsof revision 4.81 lists on its standard output file information about files opened by processes for the following
UNIX dialects:

    AIX 5.3
    FreeBSD 4.9 for x86-based systems
    FreeBSD 7.0 and 8.0 for AMD64-based systems
    Linux 2.1.72 and above for x86-based systems
    Solaris 9 and 10
```

it doesn't have to be lsof, but the idea is to get the os to just tell you.

what is the deal with multi-server programs? 
there may be a lot more complications than just detecting the ports...
because the hosts would be changing, when the app is redeployed, 
so to be usable, you would have to proxy them too.

what sort of things are people trying to run... 
I know one guy had a irc bot. is it tcp and so on?

**Comment by stolsma** [comment]
A problem is if multiple (different) applications use the same port. Now this is handled by carapace by giving a next available port. if this is not being done then all apps need to detect that the port is not available and choose another port. I don't know if it is reasonable to request that from users/app developers because lots of devs won't be developing their apps specifically for a `haibu` implementation but users of that app don't know that (and probably they also don't know how to change the code correctly)...

I think the correct implementation needs 2 solutions:
- Preferred `port` and `addr` configuration (also for multiple ports/addr!!) in the app startup configuration given to haibu. The `addr` info is already there (domains/subdomains) only a smart way of adding ports and combining that to the request from carapace needs to be invented... (maybe also the port and addr the application will give can be used to return the correct port/addr)
- A implementation of changing the requested `port` and `addr` by requesting the controlling haibu process `port` and `addr`. Haibu will then return a empty `port` and if needed an `addr` by using the data from the previous point..

These are just my ideas... ;-)

**Comment by dominictarr** [comment]
oh, I forgot about that. carapace doesn't just do detection, it also uses a different port if the port is not available.

I guess if we want to do it that way, we do need monkey patching and IPC. however, I am still an advocate of just setting the env of the app to include PORT, for the main http port.
